services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: jiwon0126
      MYSQL_DATABASE: concurrency_ticketing
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  was1:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/concurrency_ticketing?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: jiwon0126
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    volumes:
      - ./logs/was1:/app/logs
    depends_on:
      mysql:
        condition: service_healthy

  was2:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/concurrency_ticketing?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: jiwon0126
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    volumes:
      - ./logs/was2:/app/logs
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - was1
      - was2
